<?php

/* 控制层传入的参数优化 */
// 变量初始
// ...
// 接收参数
$articleRow = $this->articleRow; // 文章详情数组
//var_dump($articleRow);

?>

<table class="content" width="930" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
	<td width="5"></td>
	<td valign="top">
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
	  <tr>
		<td height="5"></td>
	  </tr>
	</table>
<?php

if (!empty($articleRow) && is_array($articleRow))
{

?>
	<table width="70%" border="0" cellpadding="8" cellspacing="1" bgcolor="#CACACA">
	  <tr>
		<td bgcolor="#FFFFFF">
		<table width="100%" border="0" cellspacing="8" cellpadding="0">
		  <tr>
			<td valign="top" style="line-height: 20px;">
			<span class="yellowBold"><?php echo $articleRow['title']; ?></span>			</td>
		  </tr>
		  <tr>
			<td valign="top" style="line-height: 20px;">发布于<?php echo date('Y年m月d日', $articleRow['created']); ?></td>
		  </tr>
		  <tr>
			<td width="100%" height="60" valign="top" style="line-height: 20px;">
			<span class=""><?php echo $articleRow['brief']; ?></span><br /></td>
		  </tr>
		  <tr>
			<td width="100%" height="60" valign="top" style="line-height: 20px;"><span class=""><?php echo (MARGIC_QUOTES_GPC ? stripslashes($articleRow['content']) : $articleRow['content']); ?></span></td>
		  </tr>
		</table>
		</td>
	  </tr>
	</table>
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
		<tr>
		  <td height="5"></td>
		</tr>
	</table>
<?php

}

?>
	</td>
	<td width="5"></td>
  </tr>
</table>
