<?php

/* 控制层传入的参数优化 */
// 变量初始
// ...
// 接收参数
$articleRecentList = $this->articleRecentList; // 最近文章列表

?>

<table class="content" width="930" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
	<td width="5"></td>
	<td valign="top">
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
	  <tr>
		<td height="5"></td>
	  </tr>
	</table>
<?php

if (!empty($articleRecentList) && is_array($articleRecentList))
{
	foreach ($articleRecentList as $value)
	{

?>
	<table width="100%" border="0" cellpadding="8" cellspacing="1" bgcolor="#CACACA">
	  <tr>
		<td bgcolor="#FFFFFF">
		<table width="100%" border="0" cellspacing="8" cellpadding="0">
		  <tr>
			<td valign="top" style="line-height: 20px;">
			<span class="yellowBold"><?php echo $value['title']; ?></span>
			</td>
			<td width="19%" rowspan="3" valign="top" style="line-height: 20px;">
			<div align="right"><img src="<?php echo $value['title_image']; ?>" width="120" height="120" alt="<?php echo $value['tags']; ?>" /></div>
			</td>
		  </tr>
		  <tr>
			<td valign="top" style="line-height: 20px;">发布于<?php echo date('Y年m月d日', $value['created']); ?></td>
		  </tr>
		  <tr>
			<td width="81%" height="60" valign="top" style="line-height: 20px;">
			<span class=""><?php echo $value['brief']; ?></span>
			</td>
			</tr>
		</table>
		</td>
	  </tr>
	</table>
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
		<tr>
		  <td height="5"></td>
		</tr>
	</table>
<?php

	}
}

?>
	</td>
	<td width="5"></td>
  </tr>
</table>
